CREATE TABLE users
(
    version         BIGINT                                              NOT NULL DEFAULT 0,
    created         TIMESTAMP                                           NOT NULL DEFAULT now(),
    updated         TIMESTAMP                                           NOT NULL DEFAULT now(),
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email           varchar(255) unique,
    hashed_password varchar
);

CREATE TRIGGER users_update_optimistic
    BEFORE UPDATE
    ON users
    FOR EACH ROW
EXECUTE PROCEDURE trigger_update_optimistic();